### ISSUE TITLE
error first time you write in username (login view)

### ISSUE THREAD

**Issue by agnes-masip** [agnes-masip/thesis-repo#24]
when i click into username after i restart the app, i always see an error in the console (doesnt break anything)

Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component.

**Comment by renskelotte48** [comment]
fixed in commit 36f0e04ab5cbe8d8dad87258f013e527629832cb [36f0e04]
